packages/api/src/rooms/rooms.controller.ts, packages/types/rooms/create-room.request.dto.ts, packages/types/rooms/room.response.dto.d.ts, packages/types/rooms/room.response.dto.ts
=> feat: update room types

packages/api/src/auth/exceptions/user-unauthorized.exception.ts, packages/api/src/auth/guards/clerk/clerk.auth.guard.ts, packages/api/src/common/exceptions/internal-server-error.exception.ts, packages/api/src/rooms/exceptions/duplicate-room-name.exception.ts, packages/api/src/rooms/rooms.controller.ts, packages/api/src/rooms/usecases/create-room.usecase.ts, packages/api/src/rooms/usecases/find-my-rooms.usecase.ts, packages/api/src/rooms/usecases/find-public-rooms.usecase.ts
- Customize some common exceptions used
- Refactor the auth guard to throw a `401` custom exception in case of user unauthenticated
- error message is as follows:
```typescript
type Error = {
statusCode: HttpStatus;
message: string[];
error: message;
}
```
=> feat: improve error handling

packages/api/src/auth/auth.module.ts, packages/api/src/auth/providers/clerk/clerk-auth-user.provider.ts, packages/api/src/auth/providers/provider.ts, packages/api/src/common/exceptions/user-not-found.exception.ts, packages/api/src/common/types/user.ts, packages/api/src/rooms/dtos/invite-user-to-room.request.dto.ts, packages/api/src/rooms/exceptions/user-already-in-room.exception.ts, packages/api/src/rooms/rooms.controller.ts, packages/api/src/rooms/rooms.module.ts, packages/api/src/rooms/rooms.repository.ts, packages/api/src/rooms/usecases/invite-user-to-room.usecase.ts, packages/contract/rooms/invite-user-to-room.request.dto.d.ts, packages/contract/rooms/invite-user-to-room.request.dto.ts
- Add invite to room controller method
- Add corresponding swagger docs
- Add validations for invite: `UserNotFound` and `AlreadyAMember`
=> feat: add invite to room feature

packages/api/src/auth/auth.controller.ts, packages/api/src/rooms/exceptions/user-not-room-member.exception.ts, packages/api/src/rooms/rooms.controller.ts, packages/api/src/rooms/rooms.module.ts, packages/api/src/rooms/rooms.repository.ts, packages/api/src/rooms/usecases/find-room-by-name.usecase.ts
- Add endpoint to get a room by name
- only members of the room can use the endpoint
=> feat: find room by name

packages/api/src/auth/auth.controller.ts
-  Add `findUser()` to fetch a single user
- Update `findUsers()` to have an optional `userIds` query param to either fetch all, or fetch those specified in the array
=> feat: find user

packages/api/src/app.module.ts, packages/api/src/chats/chats.controller.ts, packages/api/src/chats/chats.module.ts, packages/api/src/chats/chats.mongoose.providers.ts, packages/api/src/chats/chats.repository.ts, packages/api/src/chats/schemas/chat.mongoose.schema.ts, packages/api/src/chats/usecases/find-public-rooms.usecase.ts, packages/api/src/common/constants/models/chat.ts
- Add `chats` module
- Add `chats` controller
- Add `chats` repository
- Add `chats` database providers
- Add `chats` mongoose model
=> feat: new chats module

packages/web-ui/app/page.tsx, packages/web-ui/types/nav.ts
- Fix landing page typo
- Restore nav.ts types file
=> fix: typo in landing page and types error

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/on-call-deploy.yaml, .github/workflows/on-push-main.yaml, packages/api/Dockerfile
- add `cd` processes workflows
=> feat(cd): add cd workflows

.github/workflows/on-call-deploy.yaml, .github/workflows/on-push-main.yaml
Fix: A bug fix
- update workflow run
=> fix(cd): update workflow call

.github/workflows/on-push-main.yaml
- login with default github token for packages
=> feat(registry): login with default github token

packages/api/src/cache/cache.providers.ts, packages/api/src/database/database.providers.ts
Fix: A bug fix
- update mongo db connection
- update redis connection
=> fix(connections): update redis and mongo connections

packages/web-ui/app/layout.tsx, packages/web-ui/app/page.tsx, packages/web-ui/app/rooms/[room]/layout.tsx, packages/web-ui/app/rooms/[room]/page.tsx, packages/web-ui/components/chat.tsx
Fix: A bug fix
When accessing a room page, a verification is done server side to prevent non-members of that room to view that page.
Fixes [#50](https://github.com/xgeekshq/intelli-mate/issues/50)
https://github.com/xgeekshq/intelli-mate/assets/97113028/16c0321b-c444-4326-95e1-b7be6b008801
=> fix: redirect non-member users

packages/web-ui/api/apiClient.ts, packages/web-ui/components/chat.tsx, packages/web-ui/components/message.tsx, packages/web-ui/factory/create-chat.factory.ts, packages/web-ui/utils/get-user-identification.ts
Fix: A bug fix
Fixes [#47](https://github.com/xgeekshq/intelli-mate/issues/47)
=> fix: inconsistency in profile data

.github/workflows/on-push-main.yaml, packages/api/.dockerignore, packages/api/Dockerfile, packages/web-ui/Dockerfile
CI: Changes to our CI configuration files and scripts
- update build paths for nx
=> fix(buid): update build paths for nx

CONTRIBUTING.md, README.md
Docs: Documentation only changes
- add contributing guidelines for the repo
- add comprehensive readme for the repo
=> feat: docs for open source

packages/web-ui/components/icons.tsx
Fix: A bug fix
Change the LucideIcon import after the package update
=> fix: lucide icon import

packages/web-ui/app/admin/users/page.tsx, packages/web-ui/components/ui/avatar.tsx, packages/web-ui/components/ui/table.tsx
- Allow scrolling in the user list table on the admin page
https://github.com/xgeekshq/intelli-mate/assets/95644495/a637676b-b1f0-4a47-b71e-2c0f5f448a5c
=> feat: add scroll to admin user list

package-lock.json, packages/api/config/default.json, packages/api/src/ai/services/ai.service.ts, packages/api/src/ai/services/chain.service.ts, packages/api/src/ai/services/memory.service.ts, packages/api/src/app-config/app-config.service.ts, packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/usecases/add-message-to-chat.usecase.ts, packages/web-ui/components/site-header.tsx
Fix: A bug fix
- Counts the number of tokens in a conversation and summarizes if it's bigger than 3000.
Fixes [#52](https://github.com/xgeekshq/intelli-mate/issues/52)
After exceeding the limit number of tokens
=> fix: max tokens limit

packages/api/src/chats/chats.module.ts
Fix: A bug fix
Fixes https://github.com/xgeekshq/intelli-mate/pull/86
=> fix: add app config module import

packages/api/config/default.json, packages/api/src/ai/services/ai.service.ts, packages/api/src/chats/chat-socket.gateway.ts
Refactor: A code change that neither fixes a bug nor adds a feature
Change model to `gpt-3.5-turbo-16k`
It's a little bit slow 😅
https://jam.dev/c/cec4862e-599a-4717-bc6a-b4240c8d0d7d
=> fix: change ai model

packages/api/src/chats/adapters/redis-io.adapter.ts, packages/api/src/chats/chat-socket.gateway.ts
=> fix: pass socket configuration to adapter

helm/intelli-mate-api/values.yaml
=> feat: create one replica of API on deploy

packages/web-ui/app/state/socket.ts
=> fix: add credentials to socket client

packages/api/src/ai/ai.module.ts, packages/api/src/ai/services/agent-conversation.service.ts, packages/api/src/ai/services/ai.service.ts, packages/api/src/ai/services/simple-conversation-chain.service.ts, packages/api/src/ai/services/tool.service.ts, packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/chats.repository.ts, packages/api/src/chats/job-consumers/transform-doc-to-vector.job-consumer.ts, packages/api/src/chats/schemas/chat.mongoose.schema.ts, packages/api/src/chats/usecases/upload-documents-to-chat.usecase.ts, packages/api/src/common/types/chat.ts
- If documents are loaded into a chat (2 max), an agent executor is chosen to answer in the AI service facade
- If no documents are loaded into a chat, then the regular simple conversation chain will be used to answer
- Add processing document after thoughts: extract the topic and description from AI
- Add metadata to the document for the vector db consultation later
- Add tool service to handle the vector document loading
Related to #71 but still doesn't close it as we need to create the UI option to handle this.
=> feat: add agent executor to answer in AI service

packages/api/config/default.json, packages/api/src/ai/services/agent-conversation.service.ts, packages/api/src/ai/services/ai.service.ts, packages/api/src/ai/services/memory.service.ts, packages/api/src/ai/services/simple-conversation-chain.service.ts, packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/chats.module.ts, packages/api/src/chats/exceptions/redis-chat-memory-not-found.exception.ts, packages/api/src/chats/usecases/add-message-to-chat.usecase.ts
- change default token to 14500
- create a summary for chat every 14500
=> feat: optimize chat memory

packages/api/src/ai/services/agent-conversation.service.ts, packages/api/src/ai/services/ai.service.ts, packages/api/src/chats/job-consumers/transform-doc-to-vector.job-consumer.ts
Chore: Other changes that don't modify src or test files
=> chore: improve the doc ingestion

packages/api/src/chats/chats.controller.ts, packages/api/src/chats/chats.module.ts, packages/api/src/chats/chats.repository.ts, packages/api/src/chats/dtos/remove-document-from-chat.request.dto.ts, packages/api/src/chats/exceptions/document-not-found.exception.ts, packages/api/src/chats/usecases/remove-document-from-chat.usecase.ts
- add new usecase and controller endpoint to remove a document from a chat
- update chat response dto to include the files
=> feat: remove document from chat

packages/api/config/default.json, packages/api/src/ai/ai.module.ts, packages/api/src/ai/facades/ai.service.ts, packages/api/src/ai/services/agent-conversation.service.ts, packages/api/src/ai/services/tool.service.ts, packages/api/src/ai/services/vector-db.service.ts, packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/job-consumers/transform-doc-to-vector.job-consumer.ts, packages/api/src/chats/usecases/add-message-to-chat.usecase.ts, packages/api/src/chats/usecases/remove-document-from-chat.usecase.ts
- overall improvement of the doc removal
- remove vector indexes from vector db when file is removed from chat
- refactor ai service facade
- improve encapsulation for the ai facade
- refactor the vector db collection to be scoped to the `roomId`
=> feat: improve doc removal

packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/chats.module.ts, packages/api/src/chats/job-consumers/add-message-pair-to-history.job-consumer.ts, packages/api/src/chats/usecases/add-message-to-chat.usecase.ts, packages/api/src/common/constants/queues.ts, packages/api/src/common/jobs/chat-add-message-pair-to-history.job.ts
- add background job to add the question and answer in the history on the database
- refactor socket logic when receiving messages
- refactor `addMessageToChatUsecase` to extract the `shouldSummarize` logic from it
Closes [#89](https://github.com/xgeekshq/intelli-mate/issues/89)
=> feat: improve the storage of messages in history

package-lock.json, packages/web-ui/app/rooms/[room]/settings/page.tsx, packages/web-ui/components/ui/alert-dialog.tsx, packages/web-ui/components/user-search-items.tsx, packages/web-ui/package.json, packages/web-ui/types/searchList.ts
- validate if user roles match the room owner roles
- show an alert modal if the user roles and room owner roles didn't match
- add a user to the room if the roles match
Ignore all files under `components/ui` directory
https://github.com/xgeekshq/intelli-mate/assets/95644495/4b8100f9-8c8c-45a6-86da-16b3d82af75e
=> feat: add validation when adding a new user to a room

packages/api/src/ai/facades/ai.service.ts, packages/api/src/ai/services/memory.service.ts, packages/api/src/chats/chats.module.ts, packages/api/src/chats/chats.repository.ts, packages/api/src/chats/event-handlers/on-delete-room.event-handler.ts, packages/api/src/chats/job-consumers/transform-doc-to-vector.job-consumer.ts, packages/api/src/chats/usecases/delete-chat.usecase.ts, packages/api/src/chats/usecases/remove-document-from-chat.usecase.ts, packages/api/src/common/events/user-deleted-room.event.ts, packages/api/src/rooms/exceptions/room-must-be-empty-to-delete.exception.ts, packages/api/src/rooms/rooms.controller.ts, packages/api/src/rooms/rooms.module.ts, packages/api/src/rooms/rooms.repository.ts, packages/api/src/rooms/usecases/create-room.usecase.ts, packages/api/src/rooms/usecases/delete-room.usecase.ts, packages/api/src/rooms/usecases/invite-user-to-room.usecase.ts, packages/api/src/rooms/usecases/join-room.usecase.ts
- delete all documents from a room before deleting it
- delete the documents from the file system, from the vector DB matrixes and from the redis history
- adjust the AI memory service so that it also deletes the in memory history for the room
- delete the room after checking all invariants
=> feat: delete room and all associations

packages/web-ui/api/endpoints.ts, packages/web-ui/app/rooms/[room]/settings/page.tsx, packages/web-ui/components/delete-room.tsx, packages/web-ui/components/user-search-items.tsx
- Delete room form setting page
=> feat: delete room from settings page

packages/web-ui/components/chat-tools.tsx, packages/web-ui/components/chat.tsx, packages/web-ui/components/create-room-form.tsx, packages/web-ui/components/delete-room.tsx, packages/web-ui/components/document-upload-form.tsx, packages/web-ui/components/leave-room.tsx, packages/web-ui/components/room-search-items.tsx, packages/web-ui/components/update-room-form.tsx, packages/web-ui/components/user-search-items.tsx
Fix: A bug fix
- User unauthorized
=> fix: clerk unauthorized error

packages/web-ui/components/document-upload-form.tsx, packages/web-ui/components/room-header.tsx, packages/web-ui/components/rooms.tsx, packages/web-ui/components/site-header.tsx, packages/web-ui/hooks/use-browser-info.ts, packages/web-ui/hooks/use-mac-user.ts
- Add keyboard shortcuts to search for `My rooms` or `Public rooms` `command + k`
- On the room page add a keyboard shortcut to open the room setting page `command + ,`
- On the room page add a keyboard shortcut to open documents upload modal `command + u`
**Video demonstration**
https://github.com/xgeekshq/intelli-mate/assets/95644495/e41356ad-8575-4e94-a3b2-c1a3d1fc6b2f
This PR will close the next issue:
https://github.com/xgeekshq/intelli-mate/issues/156
=> feat: add keyboard utilities

packages/api/src/rooms/rooms.repository.ts, packages/api/src/rooms/usecases/create-room.usecase.ts, packages/api/src/rooms/usecases/update-room-settings.usecase.ts
Refactor: A code change that neither fixes a bug nor adds a feature
- Add verification for unique name and lower cased for creation of rooms
- Add the same verification for the update room settings usecase
=> refactor: change uniqueness check for room name

packages/api/src/main.ts, packages/contract/rooms/create-room.request.dto.ts, packages/web-ui/components/chat-tools.tsx
- Add processing file information to the chat tool bar
- Validate empty filenames with whitespaces
Fixes [#162](https://github.com/xgeekshq/intelli-mate/issues/162)
=> feat: ux improvements

packages/web-ui/components/markdown.tsx, packages/web-ui/components/message.tsx
- Add markdown parser to messages sent by the user
Fixes [#166](https://github.com/xgeekshq/intelli-mate/issues/166)
=> feat: improve the UI for the sent messages

packages/web-ui/api/requests/super-admin/admin-add-ai-model.ts, packages/web-ui/api/requests/super-admin/admin-get-ai-models.ts, packages/web-ui/api/requests/super-admin/admin-get-all-users.ts, packages/web-ui/api/requests/super-admin/update-user-roles.ts, packages/web-ui/api/requests/super-admin/validate-admin-credentials.ts, packages/web-ui/app/admin/layout.tsx, packages/web-ui/app/admin/login/page.tsx, packages/web-ui/app/admin/manage/ai-models/layout.tsx, packages/web-ui/app/admin/manage/ai-models/page.tsx, packages/web-ui/app/admin/manage/users/layout.tsx, packages/web-ui/app/admin/manage/users/page.tsx, packages/web-ui/app/admin/page.tsx, packages/web-ui/components/admin/add-ai-models-form.tsx, packages/web-ui/components/admin/admin-header.tsx, packages/web-ui/components/admin/update-roles-form.tsx, packages/web-ui/utils/get-super-admin-cookie-client.ts, packages/web-ui/utils/get-super-admin-cookie-server.ts, packages/web-ui/utils/get-url-path.ts
- add `react-query` to super admin operations
=> feat: add react-query to super admin

packages/web-ui/api/requests/rooms/delete-room.ts
Fix: A bug fix
- Fix the delete room feature
Fixes [#180](https://github.com/xgeekshq/intelli-mate/issues/180)
=> fix: fix delete room

packages/api/src/ai/facades/ai.service.ts, packages/api/src/ai/services/document-conversation-chain.service.ts, packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/job-consumers/add-message-pair-to-history.job-consumer.ts, packages/api/src/chats/schemas/chat.mongoose.schema.ts, packages/api/src/common/factories/create-chat-message.factory.ts, packages/api/src/common/types/ai-response.ts, packages/api/src/common/types/chat.ts, packages/contract/chats/add-message-to-chat.request.dto.ts, packages/contract/chats/chat-message.response.dto.ts, packages/web-ui/components/error-layout.tsx
- Save document source in AI answer message
=> feat: save document source on DB

packages/api/src/chats/chat-socket.gateway.ts, packages/api/src/chats/factory/create-socket-message.factory.ts, packages/contract/chats/socket-message.response.dto.ts, packages/web-ui/components/chat.tsx, packages/web-ui/factory/create-chat.factory.ts, packages/web-ui/types/chat.ts
- Return the document source in the message response
- Return the document source to message history
=> feat: return the document source to chat message

packages/api/src/chats/chats.controller.ts, packages/api/src/chats/exceptions/document-type-mismatch.exception.ts, packages/api/src/chats/usecases/upload-documents-to-chat.usecase.ts, packages/api/src/common/constants/files.ts
- add file type validation based on buffer signature of the mimetypes declared
Fixes [#190](https://github.com/xgeekshq/intelli-mate/issues/190)
=> feat: file type validation
